name: Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Automatically runs once a day at midnight
  workflow_dispatch:  # Allows manual trigger via the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Snake SVG
      uses: Platane/snk@master
      with:
        github_user: 'Sanctana'  # Your GitHub username
        svg_out_path: '.github/snake/github-snake-dark.svg'  # Path where the SVG will be saved
